[workspace]
members = ["crates/app", "crates/editor-core", "crates/ui", "crates/ui-macros", "crates/renderer", "crates/plugin"]
default-members = ["crates/app"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 1

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
indexing_slicing = "warn"
arithmetic_side_effects = "warn"
unreachable = "warn"
unimplemented = "warn"
unchecked_time_subtraction = "warn"
string_slice = "warn"
panic_in_result_fn = "warn"
panic = "warn"
exit = "warn"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
too_many_lines = "allow"
