[package]
name = "kama-ui-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
bytemuck = { version = "1.16", features = ["derive"] }
wgpu = "30.0.1"
winit = "0.30"

[build-dependencies]
naga = { version = "30.0.1", features = ["wgsl-in"] }
